version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_micro:latest
    ports:
      - "8000:8000"
    volumes:
      - /Users/tusharrawat/.aws/credentials:/home/app/.aws/credentials:ro
    depends_on:
      - localstack
      - aws-cli
    networks:
      - my_network

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb,lambda
    ports:
      - "4566:4566"
      - "4574:4574"
    networks:
      - my_network

  aws-cli:
    image: amazon/aws-cli:latest
    entrypoint: /bin/bash
    command: -c "while true; do sleep 1; done"
    volumes:
      - ~/.aws:/root/.aws
    networks:
      - my_network

  keycloak:
    image: sleighzy/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge