version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_micro:latest
    ports:
      - "8000:8000"
    depends_on:
      - aws_services
    networks:
      - my_network


  aws_services:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb,lambda  # Include the services you need, separated by commas
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"  # DynamoDB port
      - "4574:4574"  # Lambda port
    networks:
      - my_network


  keycloak:
    image: sleighzy/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge




